version: '3.1'

services:
  api:
    build: .
    command: bash -c 'npx sequelize-cli db:migrate && npm run dev'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/api
      - /usr/api/node_modules

  postgres:
    image: postgres:11.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: helloworld
      POSTGRES_USER: postgres
      POSTGRES_PASS: root

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
