version: '3.1'

services:
  api:
    image: docker.pkg.github.com/helloworld-repo/helloworld-api/server:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env-prod
    command: npm start
  postgres:
    image: postgres:11.2-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env-prod