name: Production Continuous Delivery

on:
  push:
    branches: 
      - development

jobs:
  build:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          name: hello-world/server
          tags: production
          workdir: server
          default_branch: master
          dockerfile: Dockerfile

  deploy:
    name: Deploy package to DigitalOcean 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy package to DigitalOcean
        uses: appleboy/ssh-action@master
        env:
            GITHUB_USERNAME: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.PRODUCTION_IP }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          password: ${{ secrets.PRODUCTION_PASSWORD }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            cd hello-world/server
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/HelloWorld-Repo/HelloWorld-API/server:production
            docker-compose -f docker-compose.prod.yml up -d


